package builtins

// dircolors and future ls --color support share the upstream uutils color tables.
var dircolorsTerms = []string{
	"Eterm",
	"alacritty*",
	"ansi",
	"*color*",
	"con[0-9]*x[0-9]*",
	"cons25",
	"console",
	"cygwin",
	"*direct*",
	"dtterm",
	"foot",
	"gnome",
	"hurd",
	"jfbterm",
	"konsole",
	"kterm",
	"linux",
	"linux-c",
	"mlterm",
	"putty",
	"rxvt*",
	"screen*",
	"st",
	"terminator",
	"tmux*",
	"vt100",
	"wezterm*",
	"xterm*",
}

type dircolorsFileType struct {
	Name string
	Key  string
	Code string
}

var dircolorsFileTypes = []dircolorsFileType{
	{Name: "RESET", Key: "rs", Code: "0"},
	{Name: "DIR", Key: "di", Code: "01;34"},
	{Name: "LINK", Key: "ln", Code: "01;36"},
	{Name: "MULTIHARDLINK", Key: "mh", Code: "00"},
	{Name: "FIFO", Key: "pi", Code: "40;33"},
	{Name: "SOCK", Key: "so", Code: "01;35"},
	{Name: "DOOR", Key: "do", Code: "01;35"},
	{Name: "BLK", Key: "bd", Code: "40;33;01"},
	{Name: "CHR", Key: "cd", Code: "40;33;01"},
	{Name: "ORPHAN", Key: "or", Code: "40;31;01"},
	{Name: "MISSING", Key: "mi", Code: "00"},
	{Name: "SETUID", Key: "su", Code: "37;41"},
	{Name: "SETGID", Key: "sg", Code: "30;43"},
	{Name: "CAPABILITY", Key: "ca", Code: "00"},
	{Name: "STICKY_OTHER_WRITABLE", Key: "tw", Code: "30;42"},
	{Name: "OTHER_WRITABLE", Key: "ow", Code: "34;42"},
	{Name: "STICKY", Key: "st", Code: "37;44"},
	{Name: "EXEC", Key: "ex", Code: "01;32"},
}

type dircolorsExtensionColor struct {
	Pattern string
	Code    string
}

var dircolorsFileColors = []dircolorsExtensionColor{
	{Pattern: ".tar", Code: "01;31"},
	{Pattern: ".tgz", Code: "01;31"},
	{Pattern: ".arc", Code: "01;31"},
	{Pattern: ".arj", Code: "01;31"},
	{Pattern: ".taz", Code: "01;31"},
	{Pattern: ".lha", Code: "01;31"},
	{Pattern: ".lz4", Code: "01;31"},
	{Pattern: ".lzh", Code: "01;31"},
	{Pattern: ".lzma", Code: "01;31"},
	{Pattern: ".tlz", Code: "01;31"},
	{Pattern: ".txz", Code: "01;31"},
	{Pattern: ".tzo", Code: "01;31"},
	{Pattern: ".t7z", Code: "01;31"},
	{Pattern: ".zip", Code: "01;31"},
	{Pattern: ".z", Code: "01;31"},
	{Pattern: ".dz", Code: "01;31"},
	{Pattern: ".gz", Code: "01;31"},
	{Pattern: ".lrz", Code: "01;31"},
	{Pattern: ".lz", Code: "01;31"},
	{Pattern: ".lzo", Code: "01;31"},
	{Pattern: ".xz", Code: "01;31"},
	{Pattern: ".zst", Code: "01;31"},
	{Pattern: ".tzst", Code: "01;31"},
	{Pattern: ".bz2", Code: "01;31"},
	{Pattern: ".bz", Code: "01;31"},
	{Pattern: ".tbz", Code: "01;31"},
	{Pattern: ".tbz2", Code: "01;31"},
	{Pattern: ".tz", Code: "01;31"},
	{Pattern: ".deb", Code: "01;31"},
	{Pattern: ".rpm", Code: "01;31"},
	{Pattern: ".jar", Code: "01;31"},
	{Pattern: ".war", Code: "01;31"},
	{Pattern: ".ear", Code: "01;31"},
	{Pattern: ".sar", Code: "01;31"},
	{Pattern: ".rar", Code: "01;31"},
	{Pattern: ".alz", Code: "01;31"},
	{Pattern: ".ace", Code: "01;31"},
	{Pattern: ".zoo", Code: "01;31"},
	{Pattern: ".cpio", Code: "01;31"},
	{Pattern: ".7z", Code: "01;31"},
	{Pattern: ".rz", Code: "01;31"},
	{Pattern: ".cab", Code: "01;31"},
	{Pattern: ".wim", Code: "01;31"},
	{Pattern: ".swm", Code: "01;31"},
	{Pattern: ".dwm", Code: "01;31"},
	{Pattern: ".esd", Code: "01;31"},
	{Pattern: ".avif", Code: "01;35"},
	{Pattern: ".jpg", Code: "01;35"},
	{Pattern: ".jpeg", Code: "01;35"},
	{Pattern: ".mjpg", Code: "01;35"},
	{Pattern: ".mjpeg", Code: "01;35"},
	{Pattern: ".gif", Code: "01;35"},
	{Pattern: ".bmp", Code: "01;35"},
	{Pattern: ".pbm", Code: "01;35"},
	{Pattern: ".pgm", Code: "01;35"},
	{Pattern: ".ppm", Code: "01;35"},
	{Pattern: ".tga", Code: "01;35"},
	{Pattern: ".xbm", Code: "01;35"},
	{Pattern: ".xpm", Code: "01;35"},
	{Pattern: ".tif", Code: "01;35"},
	{Pattern: ".tiff", Code: "01;35"},
	{Pattern: ".png", Code: "01;35"},
	{Pattern: ".svg", Code: "01;35"},
	{Pattern: ".svgz", Code: "01;35"},
	{Pattern: ".mng", Code: "01;35"},
	{Pattern: ".pcx", Code: "01;35"},
	{Pattern: ".mov", Code: "01;35"},
	{Pattern: ".mpg", Code: "01;35"},
	{Pattern: ".mpeg", Code: "01;35"},
	{Pattern: ".m2v", Code: "01;35"},
	{Pattern: ".mkv", Code: "01;35"},
	{Pattern: ".webm", Code: "01;35"},
	{Pattern: ".webp", Code: "01;35"},
	{Pattern: ".ogm", Code: "01;35"},
	{Pattern: ".mp4", Code: "01;35"},
	{Pattern: ".m4v", Code: "01;35"},
	{Pattern: ".mp4v", Code: "01;35"},
	{Pattern: ".vob", Code: "01;35"},
	{Pattern: ".qt", Code: "01;35"},
	{Pattern: ".nuv", Code: "01;35"},
	{Pattern: ".wmv", Code: "01;35"},
	{Pattern: ".asf", Code: "01;35"},
	{Pattern: ".rm", Code: "01;35"},
	{Pattern: ".rmvb", Code: "01;35"},
	{Pattern: ".flc", Code: "01;35"},
	{Pattern: ".avi", Code: "01;35"},
	{Pattern: ".fli", Code: "01;35"},
	{Pattern: ".flv", Code: "01;35"},
	{Pattern: ".gl", Code: "01;35"},
	{Pattern: ".dl", Code: "01;35"},
	{Pattern: ".xcf", Code: "01;35"},
	{Pattern: ".xwd", Code: "01;35"},
	{Pattern: ".yuv", Code: "01;35"},
	{Pattern: ".cgm", Code: "01;35"},
	{Pattern: ".emf", Code: "01;35"},
	{Pattern: ".ogv", Code: "01;35"},
	{Pattern: ".ogx", Code: "01;35"},
	{Pattern: ".aac", Code: "00;36"},
	{Pattern: ".au", Code: "00;36"},
	{Pattern: ".flac", Code: "00;36"},
	{Pattern: ".m4a", Code: "00;36"},
	{Pattern: ".mid", Code: "00;36"},
	{Pattern: ".midi", Code: "00;36"},
	{Pattern: ".mka", Code: "00;36"},
	{Pattern: ".mp3", Code: "00;36"},
	{Pattern: ".mpc", Code: "00;36"},
	{Pattern: ".ogg", Code: "00;36"},
	{Pattern: ".ra", Code: "00;36"},
	{Pattern: ".wav", Code: "00;36"},
	{Pattern: ".oga", Code: "00;36"},
	{Pattern: ".opus", Code: "00;36"},
	{Pattern: ".spx", Code: "00;36"},
	{Pattern: ".xspf", Code: "00;36"},
	{Pattern: "*~", Code: "00;90"},
	{Pattern: "*#", Code: "00;90"},
	{Pattern: ".bak", Code: "00;90"},
	{Pattern: ".old", Code: "00;90"},
	{Pattern: ".orig", Code: "00;90"},
	{Pattern: ".part", Code: "00;90"},
	{Pattern: ".rej", Code: "00;90"},
	{Pattern: ".swp", Code: "00;90"},
	{Pattern: ".tmp", Code: "00;90"},
	{Pattern: ".dpkg-dist", Code: "00;90"},
	{Pattern: ".dpkg-old", Code: "00;90"},
	{Pattern: ".ucf-dist", Code: "00;90"},
	{Pattern: ".ucf-new", Code: "00;90"},
	{Pattern: ".ucf-old", Code: "00;90"},
	{Pattern: ".rpmnew", Code: "00;90"},
	{Pattern: ".rpmorig", Code: "00;90"},
	{Pattern: ".rpmsave", Code: "00;90"},
}

var dircolorsAttributeCodes = map[string]string{
	"normal":                "no",
	"norm":                  "no",
	"file":                  "fi",
	"reset":                 "rs",
	"dir":                   "di",
	"lnk":                   "ln",
	"link":                  "ln",
	"symlink":               "ln",
	"orphan":                "or",
	"missing":               "mi",
	"fifo":                  "pi",
	"pipe":                  "pi",
	"sock":                  "so",
	"blk":                   "bd",
	"block":                 "bd",
	"chr":                   "cd",
	"char":                  "cd",
	"door":                  "do",
	"exec":                  "ex",
	"left":                  "lc",
	"leftcode":              "lc",
	"right":                 "rc",
	"rightcode":             "rc",
	"end":                   "ec",
	"endcode":               "ec",
	"suid":                  "su",
	"setuid":                "su",
	"sgid":                  "sg",
	"setgid":                "sg",
	"sticky":                "st",
	"other_writable":        "ow",
	"owr":                   "ow",
	"sticky_other_writable": "tw",
	"owt":                   "tw",
	"capability":            "ca",
	"multihardlink":         "mh",
	"clrtoeol":              "cl",
}
