package builtins

import "github.com/veypi/vsh/commands"

func DefaultRegistry() *commands.Registry {
	cmds := []commands.Command{
		NewCDResolve(),
		NewEcho(),
		NewPwd(),
		NewTouch(),
		NewCat(),
		NewCP(),
		NewMV(),
		NewLN(),
		NewLink(),
		NewLS(),
		NewDir(),
		NewDircolors(),
		NewRmdir(),
		NewReadlink(),
		NewStat(),
		NewBasename(),
		NewDirname(),
		NewTree(),
		NewDU(),
		NewFile(),
		NewFind(),
		NewClear(),
		NewGrep(),
		NewEGrep(),
		NewFGrep(),
		NewRG(),
		NewHead(),
		NewTail(),
		NewWC(),
		NewSort(),
		NewUniq(),
		NewCut(),
		NewSed(),
		NewPrintf(),
		NewTee(),
		NewEnv(),
		NewPrintEnv(),
		NewTest(),
		NewBracketTest(),
		NewTrue(),
		NewFalse(),
		NewWhich(),
		NewHelp(),
		NewCompadjust(),
		NewCompgen(),
		NewComplete(),
		NewCompopt(),
		NewDate(),
		NewID(),
		NewWhoami(),
		NewUptime(),
		NewSleep(),
		NewHistory(),
		NewTimeout(),
		NewXArgs(),
		NewXan(),
		NewYes(),
		NewBash(),
		NewSh(),
		NewMksh(),
		NewZsh(),
		NewBats(),
		NewComm(),
		NewColumn(),
		NewPaste(),
		NewTR(),
		NewRev(),
		NewNL(),
		NewJoin(),
		NewSplit(),
		NewTac(),
		NewDiff(),
		NewOD(),
		NewSeq(),
		NewBase32(),
		NewBase64(),
		NewArch(),
		NewBasenc(),
		NewChgrp(),
		NewCksum(),
		NewCsplit(),
		NewDd(),

		NewExpand(),
		NewFactor(),
		NewFmt(),
		NewFold(),
		NewTar(),
		NewGzip(),
		NewGunzip(),
		NewZCat(),
		NewGroups(),
		NewHostid(),
		NewHostname(),
		NewChmod(),
		NewChown(),
		NewInstall(),
		NewKill(),
		NewMkdir(),
		NewMkfifo(),
		NewLogname(),
		NewMktemp(),
		NewRM(),
		NewNproc(),
		NewNumfmt(),
		NewPathchk(),
		NewPinky(),
		NewPr(),
		NewPtx(),
		NewRealpath(),
		NewShuf(),
		NewSum(),
		NewTruncate(),
		NewTsort(),
		NewTty(),
		NewUname(),
		NewUnexpand(),
		NewUnlink(),
		NewUsers(),
		NewVdir(),
		NewB2Sum(),
		NewExpr(),
		NewMD5Sum(),
		NewSHA1Sum(),
		NewSHA224Sum(),
		NewSHA256Sum(),
		NewSHA384Sum(),
		NewSHA512Sum(),
		NewStrings(),
		NewUmask(),
		NewWho(),
	}
	return commands.NewRegistry(cmds...)
}

func EnsureNetworkCommands(registry commands.CommandRegistry) error {
	if registry == nil {
		return nil
	}
	if _, ok := registry.Lookup("curl"); ok {
		return nil
	}
	return registry.Register(NewCurl())
}
